# ABOUTME: Jujutsu (jj) configuration file with settings ported from git config
# ABOUTME: Includes delta pager, nvim merge editor, GPG signing, and user settings
"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Jonas Bulik"
email = "jonas@bulik.dev"

[ui]
pager = "delta"
default-command = "status"

[merge-tools.nvim]
program = "nvim"
# Adapted from git mergetool "nvim" cmd configuration
merge-args = [
  "-d",
  "-c",
  "wincmd l",
  "-c",
  "norm ]c",
  "$left",
  "$output",
  "$right",
]

[signing]
behavior = "keep"        # Options: keep, sign, drop (keep existing signatures, don't auto-sign)
backend = "gpg"
key = "F19710F77B1A3CBC"

[revset-aliases]
"trunk()" = "main@origin"

[revset]
log = "working_copies():: | ancestors(remote_bookmarks().., 2) | trunk() | fork_point(@ | trunk())::"
