#!/usr/bin/env fish
# fish completion support for linear v1.9.1

function __fish_linear_using_command
  set -l cmds __linear __linear_auth __linear_auth_login __linear_auth_logout __linear_auth_list __linear_auth_default __linear_auth_token __linear_auth_whoami __linear_issue __linear_issue_id __linear_issue_list __linear_issue_title __linear_issue_start __linear_issue_view __linear_issue_url __linear_issue_describe __linear_issue_commits __linear_issue_pull_request __linear_issue_delete __linear_issue_create __linear_issue_update __linear_issue_comment __linear_issue_comment_add __linear_issue_comment_update __linear_issue_comment_list __linear_issue_attach __linear_team __linear_team_create __linear_team_delete __linear_team_list __linear_team_id __linear_team_autolinks __linear_team_members __linear_project __linear_project_list __linear_project_view __linear_project_create __linear_project_update __linear_project_update_create __linear_project_update_list __linear_milestone __linear_milestone_list __linear_milestone_view __linear_milestone_create __linear_milestone_update __linear_milestone_delete __linear_initiative __linear_initiative_list __linear_initiative_view __linear_initiative_create __linear_initiative_archive __linear_initiative_update __linear_initiative_unarchive __linear_initiative_delete __linear_initiative_add_project __linear_initiative_remove_project __linear_initiative_update __linear_initiative_update_create __linear_initiative_update_list __linear_label __linear_label_list __linear_label_create __linear_label_delete __linear_document __linear_document_list __linear_document_view __linear_document_create __linear_document_update __linear_document_delete __linear_completions __linear_completions_bash __linear_completions_fish __linear_completions_zsh __linear_config __linear_schema
  set -l words (commandline -opc)
  set -l cmd "_"
  for word in $words
    switch $word
      case '-*'
        continue
      case '*'
        set word (string replace -r -a '\W' '_' $word)
        set -l cmd_tmp $cmd"_$word"
        if contains $cmd_tmp $cmds
          set cmd $cmd_tmp
        end
    end
  end
  if test "$cmd" = "$argv[1]"
    return 0
  end
  return 1
end

complete -c linear -n '__fish_linear_using_command __linear' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear' -s V -l version -x -k -f -d 'Show the version number for this program.'
complete -c linear -n '__fish_linear_using_command __linear' -s w -l workspace -k -f -r -a '(linear completions complete string )' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a auth -d 'Manage Linear authentication'
complete -c linear -n '__fish_linear_using_command __linear_auth' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth' -s w -l workspace -k -f -r -a '(linear completions complete string auth)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_auth' -k -f -a login -d 'Add a workspace credential'
complete -c linear -n '__fish_linear_using_command __linear_auth_login' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth_login' -s w -l workspace -k -f -r -a '(linear completions complete string auth login)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_auth_login' -s k -l key -k -f -r -a '(linear completions complete string auth login)' -d 'API key (prompted if not provided)'
complete -c linear -n '__fish_linear_using_command __linear_auth' -k -f -a logout -d 'Remove a workspace credential'
complete -c linear -n '__fish_linear_using_command __linear_auth_logout' -k -f -a '(linear completions complete string auth logout)'
complete -c linear -n '__fish_linear_using_command __linear_auth_logout' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth_logout' -s w -l workspace -k -f -r -a '(linear completions complete string auth logout)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_auth_logout' -s f -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_auth' -k -f -a list -d 'List configured workspaces'
complete -c linear -n '__fish_linear_using_command __linear_auth_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth_list' -s w -l workspace -k -f -r -a '(linear completions complete string auth list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_auth' -k -f -a default -d 'Set the default workspace'
complete -c linear -n '__fish_linear_using_command __linear_auth_default' -k -f -a '(linear completions complete string auth default)'
complete -c linear -n '__fish_linear_using_command __linear_auth_default' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth_default' -s w -l workspace -k -f -r -a '(linear completions complete string auth default)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_auth' -k -f -a token -d 'Print the configured API token'
complete -c linear -n '__fish_linear_using_command __linear_auth_token' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth_token' -s w -l workspace -k -f -r -a '(linear completions complete string auth token)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_auth' -k -f -a whoami -d 'Print information about the authenticated user'
complete -c linear -n '__fish_linear_using_command __linear_auth_whoami' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_auth_whoami' -s w -l workspace -k -f -r -a '(linear completions complete string auth whoami)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a issue -d 'Manage Linear issues'
complete -c linear -n '__fish_linear_using_command __linear_issue' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue' -s w -l workspace -k -f -r -a '(linear completions complete string issue)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a id -d 'Print the issue based on the current git branch'
complete -c linear -n '__fish_linear_using_command __linear_issue_id' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_id' -s w -l workspace -k -f -r -a '(linear completions complete string issue id)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a list -d 'List your issues'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s w -l workspace -k -f -r -a '(linear completions complete string issue list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s s -l state -k -f -r -a '(linear completions complete state issue list)' -d 'Filter by issue state (can be repeated for multiple states)'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l all-states -k -f -d 'Show issues from all states'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l assignee -k -f -r -a '(linear completions complete string issue list)' -d 'Filter by assignee (username)'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s A -l all-assignees -k -f -d 'Show issues for all assignees'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s U -l unassigned -k -f -d 'Show only unassigned issues'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l sort -k -f -r -a '(linear completions complete sort issue list)' -d 'Sort order (can also be set via LINEAR_ISSUE_SORT)'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l team -k -f -r -a '(linear completions complete string issue list)' -d 'Team to list issues for (if not your default team)'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l project -k -f -r -a '(linear completions complete string issue list)' -d 'Filter by project name'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l limit -k -f -r -a '(linear completions complete number issue list)' -d 'Maximum number of issues to fetch (default: 50, use 0 for unlimited)'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s w -l web -k -f -d 'Open in web browser'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -s a -l app -k -f -d 'Open in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_issue_list' -l no-pager -k -f -d 'Disable automatic paging for long output'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a title -d 'Print the issue title'
complete -c linear -n '__fish_linear_using_command __linear_issue_title' -k -f -a '(linear completions complete string issue title)'
complete -c linear -n '__fish_linear_using_command __linear_issue_title' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_title' -s w -l workspace -k -f -r -a '(linear completions complete string issue title)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a start -d 'Start working on an issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -k -f -a '(linear completions complete string issue start)'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -s w -l workspace -k -f -r -a '(linear completions complete string issue start)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -s A -l all-assignees -k -f -d 'Show issues for all assignees'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -s U -l unassigned -k -f -d 'Show only unassigned issues'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -s f -l from-ref -k -f -r -a '(linear completions complete string issue start)' -d 'Git ref to create new branch from'
complete -c linear -n '__fish_linear_using_command __linear_issue_start' -s b -l branch -k -f -r -a '(linear completions complete string issue start)' -d 'Custom branch name to use instead of the issue identifier'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a view -d 'View issue details (default) or open in browser/app'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -k -f -a '(linear completions complete string issue view)'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -s w -l workspace -k -f -r -a '(linear completions complete string issue view)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -s w -l web -k -f -d 'Open in web browser'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -s a -l app -k -f -d 'Open in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -l no-comments -k -f -d 'Exclude comments from the output'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -l no-pager -k -f -d 'Disable automatic paging for long output'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -s j -l json -k -f -d 'Output issue data as JSON'
complete -c linear -n '__fish_linear_using_command __linear_issue_view' -l no-download -k -f -d 'Keep remote URLs instead of downloading files'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a url -d 'Print the issue URL'
complete -c linear -n '__fish_linear_using_command __linear_issue_url' -k -f -a '(linear completions complete string issue url)'
complete -c linear -n '__fish_linear_using_command __linear_issue_url' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_url' -s w -l workspace -k -f -r -a '(linear completions complete string issue url)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a describe -d 'Print the issue title and Linear-issue trailer'
complete -c linear -n '__fish_linear_using_command __linear_issue_describe' -k -f -a '(linear completions complete string issue describe)'
complete -c linear -n '__fish_linear_using_command __linear_issue_describe' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_describe' -s w -l workspace -k -f -r -a '(linear completions complete string issue describe)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_describe' -s r -l references -k -f -d 'Use \'References\' instead of \'Fixes\' for the Linear issue link'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a commits -d 'Show all commits for a Linear issue (jj only)'
complete -c linear -n '__fish_linear_using_command __linear_issue_commits' -k -f -a '(linear completions complete string issue commits)'
complete -c linear -n '__fish_linear_using_command __linear_issue_commits' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_commits' -s w -l workspace -k -f -r -a '(linear completions complete string issue commits)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a pull-request -d 'Create a GitHub pull request with issue details'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -k -f -a '(linear completions complete string issue pull-request)'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -s w -l workspace -k -f -r -a '(linear completions complete string issue pull-request)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -l base -k -f -r -a '(linear completions complete string issue pull-request)' -d 'The branch into which you want your code merged'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -l draft -k -f -d 'Create the pull request as a draft'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -s t -l title -k -f -r -a '(linear completions complete string issue pull-request)' -d 'Optional title for the pull request (Linear issue ID will be prefixed)'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -l web -k -f -d 'Open the pull request in the browser after creating it'
complete -c linear -n '__fish_linear_using_command __linear_issue_pull_request' -l head -k -f -r -a '(linear completions complete string issue pull-request)' -d 'The branch that contains commits for your pull request'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a delete -d 'Delete an issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -k -f -a '(linear completions complete string issue delete)'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -s w -l workspace -k -f -r -a '(linear completions complete string issue delete)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -s y -l confirm -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -l bulk -k -f -r -a '(linear completions complete string issue delete)' -d 'Delete multiple issues by identifier (e.g., TC-123 TC-124)'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -l bulk-file -k -f -r -a '(linear completions complete string issue delete)' -d 'Read issue identifiers from a file (one per line)'
complete -c linear -n '__fish_linear_using_command __linear_issue_delete' -l bulk-stdin -k -f -d 'Read issue identifiers from stdin'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a create -d 'Create a linear issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s w -l workspace -k -f -r -a '(linear completions complete string issue create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l start -k -f -d 'Start the issue after creation'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s a -l assignee -k -f -r -a '(linear completions complete string issue create)' -d 'Assign the issue to \'self\' or someone (by username or name)'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l due-date -k -f -r -a '(linear completions complete string issue create)' -d 'Due date of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s p -l parent -k -f -r -a '(linear completions complete string issue create)' -d 'Parent issue (if any) as a team_number code'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l priority -k -f -r -a '(linear completions complete number issue create)' -d 'Priority of the issue (1-4, descending priority)'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l estimate -k -f -r -a '(linear completions complete number issue create)' -d 'Points estimate of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s d -l description -k -f -r -a '(linear completions complete string issue create)' -d 'Description of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s l -l label -k -f -r -a '(linear completions complete string issue create)' -d 'Issue label associated with the issue. May be repeated.'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l team -k -f -r -a '(linear completions complete string issue create)' -d 'Team associated with the issue (if not your default team)'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l project -k -f -r -a '(linear completions complete string issue create)' -d 'Name of the project with the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s s -l state -k -f -r -a '(linear completions complete string issue create)' -d 'Workflow state for the issue (by name or type)'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l no-use-default-template -k -f -d 'Do not use default template for the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -l no-interactive -k -f -d 'Disable interactive prompts'
complete -c linear -n '__fish_linear_using_command __linear_issue_create' -s t -l title -k -f -r -a '(linear completions complete string issue create)' -d 'Title of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a update -d 'Update a linear issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -k -f -a '(linear completions complete string issue update)'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s w -l workspace -k -f -r -a '(linear completions complete string issue update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s a -l assignee -k -f -r -a '(linear completions complete string issue update)' -d 'Assign the issue to \'self\' or someone (by username or name)'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -l due-date -k -f -r -a '(linear completions complete string issue update)' -d 'Due date of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s p -l parent -k -f -r -a '(linear completions complete string issue update)' -d 'Parent issue (if any) as a team_number code'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -l priority -k -f -r -a '(linear completions complete number issue update)' -d 'Priority of the issue (1-4, descending priority)'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -l estimate -k -f -r -a '(linear completions complete number issue update)' -d 'Points estimate of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s d -l description -k -f -r -a '(linear completions complete string issue update)' -d 'Description of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s l -l label -k -f -r -a '(linear completions complete string issue update)' -d 'Issue label associated with the issue. May be repeated.'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -l team -k -f -r -a '(linear completions complete string issue update)' -d 'Team associated with the issue (if not your default team)'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -l project -k -f -r -a '(linear completions complete string issue update)' -d 'Name of the project with the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s s -l state -k -f -r -a '(linear completions complete string issue update)' -d 'Workflow state for the issue (by name or type)'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_issue_update' -s t -l title -k -f -r -a '(linear completions complete string issue update)' -d 'Title of the issue'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a comment -d 'Manage issue comments'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment' -s w -l workspace -k -f -r -a '(linear completions complete string issue comment)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment' -k -f -a add -d 'Add a comment to an issue or reply to a comment'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_add' -k -f -a '(linear completions complete string issue comment add)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_add' -s w -l workspace -k -f -r -a '(linear completions complete string issue comment add)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_add' -s b -l body -k -f -r -a '(linear completions complete string issue comment add)' -d 'Comment body text'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_add' -s p -l parent -k -f -r -a '(linear completions complete string issue comment add)' -d 'Parent comment ID for replies'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_add' -s a -l attach -k -f -r -a '(linear completions complete string issue comment add)' -d 'Attach a file to the comment (can be used multiple times)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment' -k -f -a update -d 'Update an existing comment'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_update' -k -f -a '(linear completions complete string issue comment update)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_update' -s w -l workspace -k -f -r -a '(linear completions complete string issue comment update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_update' -s b -l body -k -f -r -a '(linear completions complete string issue comment update)' -d 'New comment body text'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment' -k -f -a list -d 'List comments for an issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_list' -k -f -a '(linear completions complete string issue comment list)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_list' -s w -l workspace -k -f -r -a '(linear completions complete string issue comment list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_comment_list' -s j -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_issue' -k -f -a attach -d 'Attach a file to an issue'
complete -c linear -n '__fish_linear_using_command __linear_issue_attach' -k -f -a '(linear completions complete string issue attach)'
complete -c linear -n '__fish_linear_using_command __linear_issue_attach' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_issue_attach' -s w -l workspace -k -f -r -a '(linear completions complete string issue attach)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_issue_attach' -s t -l title -k -f -r -a '(linear completions complete string issue attach)' -d 'Custom title for the attachment'
complete -c linear -n '__fish_linear_using_command __linear_issue_attach' -s c -l comment -k -f -r -a '(linear completions complete string issue attach)' -d 'Add a comment body linked to the attachment'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a team -d 'Manage Linear teams'
complete -c linear -n '__fish_linear_using_command __linear_team' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team' -s w -l workspace -k -f -r -a '(linear completions complete string team)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team' -k -f -a create -d 'Create a linear team'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -s w -l workspace -k -f -r -a '(linear completions complete string team create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -s n -l name -k -f -r -a '(linear completions complete string team create)' -d 'Name of the team'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -s d -l description -k -f -r -a '(linear completions complete string team create)' -d 'Description of the team'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -s k -l key -k -f -r -a '(linear completions complete string team create)' -d 'Team key (if not provided, will be generated from name)'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -l private -k -f -d 'Make the team private'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_team_create' -l no-interactive -k -f -d 'Disable interactive prompts'
complete -c linear -n '__fish_linear_using_command __linear_team' -k -f -a delete -d 'Delete a Linear team'
complete -c linear -n '__fish_linear_using_command __linear_team_delete' -k -f -a '(linear completions complete string team delete)'
complete -c linear -n '__fish_linear_using_command __linear_team_delete' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team_delete' -s w -l workspace -k -f -r -a '(linear completions complete string team delete)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team_delete' -l move-issues -k -f -r -a '(linear completions complete string team delete)' -d 'Move all issues to another team before deletion'
complete -c linear -n '__fish_linear_using_command __linear_team_delete' -s y -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_team' -k -f -a list -d 'List teams'
complete -c linear -n '__fish_linear_using_command __linear_team_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team_list' -s w -l workspace -k -f -r -a '(linear completions complete string team list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team_list' -s w -l web -k -f -d 'Open in web browser'
complete -c linear -n '__fish_linear_using_command __linear_team_list' -s a -l app -k -f -d 'Open in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_team' -k -f -a id -d 'Print the configured team id'
complete -c linear -n '__fish_linear_using_command __linear_team_id' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team_id' -s w -l workspace -k -f -r -a '(linear completions complete string team id)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team' -k -f -a autolinks -d 'Configure GitHub repository autolinks for Linear issues with this team prefix'
complete -c linear -n '__fish_linear_using_command __linear_team_autolinks' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team_autolinks' -s w -l workspace -k -f -r -a '(linear completions complete string team autolinks)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team' -k -f -a members -d 'List team members'
complete -c linear -n '__fish_linear_using_command __linear_team_members' -k -f -a '(linear completions complete string team members)'
complete -c linear -n '__fish_linear_using_command __linear_team_members' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_team_members' -s w -l workspace -k -f -r -a '(linear completions complete string team members)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_team_members' -s a -l all -k -f -d 'Include inactive members'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a project -d 'Manage Linear projects'
complete -c linear -n '__fish_linear_using_command __linear_project' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project' -s w -l workspace -k -f -r -a '(linear completions complete string project)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project' -k -f -a list -d 'List projects'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -s w -l workspace -k -f -r -a '(linear completions complete string project list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -l team -k -f -r -a '(linear completions complete string project list)' -d 'Filter by team key'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -l all-teams -k -f -d 'Show projects from all teams'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -l status -k -f -r -a '(linear completions complete string project list)' -d 'Filter by status name'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -s w -l web -k -f -d 'Open in web browser'
complete -c linear -n '__fish_linear_using_command __linear_project_list' -s a -l app -k -f -d 'Open in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_project' -k -f -a view -d 'View project details'
complete -c linear -n '__fish_linear_using_command __linear_project_view' -k -f -a '(linear completions complete string project view)'
complete -c linear -n '__fish_linear_using_command __linear_project_view' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project_view' -s w -l workspace -k -f -r -a '(linear completions complete string project view)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project_view' -s w -l web -k -f -d 'Open in web browser'
complete -c linear -n '__fish_linear_using_command __linear_project_view' -s a -l app -k -f -d 'Open in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_project' -k -f -a create -d 'Create a new Linear project'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s w -l workspace -k -f -r -a '(linear completions complete string project create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s n -l name -k -f -r -a '(linear completions complete string project create)' -d 'Project name (required)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s d -l description -k -f -r -a '(linear completions complete string project create)' -d 'Project description'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s t -l team -k -f -r -a '(linear completions complete string project create)' -d 'Team key (required, can be repeated for multiple teams)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s l -l lead -k -f -r -a '(linear completions complete string project create)' -d 'Project lead (username, email, or @me)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s s -l status -k -f -r -a '(linear completions complete string project create)' -d 'Project status (planned, started, paused, completed, canceled, backlog)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -l start-date -k -f -r -a '(linear completions complete string project create)' -d 'Start date (YYYY-MM-DD)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -l target-date -k -f -r -a '(linear completions complete string project create)' -d 'Target completion date (YYYY-MM-DD)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -l initiative -k -f -r -a '(linear completions complete string project create)' -d 'Add to initiative immediately (ID, slug, or name)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -s i -l interactive -k -f -d 'Interactive mode (default if no flags provided)'
complete -c linear -n '__fish_linear_using_command __linear_project_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a project-update -d 'Manage project status updates'
complete -c linear -n '__fish_linear_using_command __linear_project_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project_update' -s w -l workspace -k -f -r -a '(linear completions complete string project-update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project_update' -k -f -a create -d 'Create a new status update for a project'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -k -f -a '(linear completions complete string project-update create)'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -s w -l workspace -k -f -r -a '(linear completions complete string project-update create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -l body -k -f -r -a '(linear completions complete string project-update create)' -d 'Update content (inline)'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -l body-file -k -f -r -a '(linear completions complete string project-update create)' -d 'Read content from file'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -l health -k -f -r -a '(linear completions complete string project-update create)' -d 'Project health status (onTrack, atRisk, offTrack)'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -s i -l interactive -k -f -d 'Interactive mode with prompts'
complete -c linear -n '__fish_linear_using_command __linear_project_update_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_project_update' -k -f -a list -d 'List status updates for a project'
complete -c linear -n '__fish_linear_using_command __linear_project_update_list' -k -f -a '(linear completions complete string project-update list)'
complete -c linear -n '__fish_linear_using_command __linear_project_update_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_project_update_list' -s w -l workspace -k -f -r -a '(linear completions complete string project-update list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_project_update_list' -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_project_update_list' -l limit -k -f -r -a '(linear completions complete number project-update list)' -d 'Limit results'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a milestone -d 'Manage Linear project milestones'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -s w -l workspace -k -f -r -a '(linear completions complete string milestone)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -k -f -a list -d 'List milestones for a project'
complete -c linear -n '__fish_linear_using_command __linear_milestone_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_milestone_list' -s w -l workspace -k -f -r -a '(linear completions complete string milestone list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_list' -l project -k -f -r -a '(linear completions complete string milestone list)' -d 'Project ID'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -k -f -a view -d 'View milestone details'
complete -c linear -n '__fish_linear_using_command __linear_milestone_view' -k -f -a '(linear completions complete string milestone view)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_view' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_milestone_view' -s w -l workspace -k -f -r -a '(linear completions complete string milestone view)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -k -f -a create -d 'Create a new project milestone'
complete -c linear -n '__fish_linear_using_command __linear_milestone_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_milestone_create' -s w -l workspace -k -f -r -a '(linear completions complete string milestone create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_create' -l project -k -f -r -a '(linear completions complete string milestone create)' -d 'Project ID'
complete -c linear -n '__fish_linear_using_command __linear_milestone_create' -l name -k -f -r -a '(linear completions complete string milestone create)' -d 'Milestone name'
complete -c linear -n '__fish_linear_using_command __linear_milestone_create' -l description -k -f -r -a '(linear completions complete string milestone create)' -d 'Milestone description'
complete -c linear -n '__fish_linear_using_command __linear_milestone_create' -l target-date -k -f -r -a '(linear completions complete string milestone create)' -d 'Target date (YYYY-MM-DD)'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -k -f -a update -d 'Update an existing project milestone'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -k -f -a '(linear completions complete string milestone update)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -s w -l workspace -k -f -r -a '(linear completions complete string milestone update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -l name -k -f -r -a '(linear completions complete string milestone update)' -d 'Milestone name'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -l description -k -f -r -a '(linear completions complete string milestone update)' -d 'Milestone description'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -l target-date -k -f -r -a '(linear completions complete string milestone update)' -d 'Target date (YYYY-MM-DD)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_update' -l project -k -f -r -a '(linear completions complete string milestone update)' -d 'Move to a different project'
complete -c linear -n '__fish_linear_using_command __linear_milestone' -k -f -a delete -d 'Delete a project milestone'
complete -c linear -n '__fish_linear_using_command __linear_milestone_delete' -k -f -a '(linear completions complete string milestone delete)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_delete' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_milestone_delete' -s w -l workspace -k -f -r -a '(linear completions complete string milestone delete)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_milestone_delete' -s f -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a initiative -d 'Manage Linear initiatives'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -s w -l workspace -k -f -r -a '(linear completions complete string initiative)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a list -d 'List initiatives'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s w -l workspace -k -f -r -a '(linear completions complete string initiative list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s s -l status -k -f -r -a '(linear completions complete string initiative list)' -d 'Filter by status (active, planned, completed)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -l all-statuses -k -f -d 'Show all statuses (default: active only)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s o -l owner -k -f -r -a '(linear completions complete string initiative list)' -d 'Filter by owner (username or email)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s w -l web -k -f -d 'Open initiatives page in web browser'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s a -l app -k -f -d 'Open initiatives page in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -s j -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_initiative_list' -l archived -k -f -d 'Include archived initiatives'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a view -d 'View initiative details'
complete -c linear -n '__fish_linear_using_command __linear_initiative_view' -k -f -a '(linear completions complete string initiative view)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_view' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_view' -s w -l workspace -k -f -r -a '(linear completions complete string initiative view)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_view' -s w -l web -k -f -d 'Open in web browser'
complete -c linear -n '__fish_linear_using_command __linear_initiative_view' -s a -l app -k -f -d 'Open in Linear.app'
complete -c linear -n '__fish_linear_using_command __linear_initiative_view' -s j -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a create -d 'Create a new Linear initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s w -l workspace -k -f -r -a '(linear completions complete string initiative create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s n -l name -k -f -r -a '(linear completions complete string initiative create)' -d 'Initiative name (required)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s d -l description -k -f -r -a '(linear completions complete string initiative create)' -d 'Initiative description'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s s -l status -k -f -r -a '(linear completions complete string initiative create)' -d 'Status: planned, active, completed (default: planned)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s o -l owner -k -f -r -a '(linear completions complete string initiative create)' -d 'Owner (username, email, or @me for yourself)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -l target-date -k -f -r -a '(linear completions complete string initiative create)' -d 'Target completion date (YYYY-MM-DD)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s c -l color -k -f -r -a '(linear completions complete string initiative create)' -d 'Color hex code (e.g., #5E6AD2)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -l icon -k -f -r -a '(linear completions complete string initiative create)' -d 'Icon name'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -s i -l interactive -k -f -d 'Interactive mode (default if no flags provided)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a archive -d 'Archive a Linear initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -k -f -a '(linear completions complete string initiative archive)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -s w -l workspace -k -f -r -a '(linear completions complete string initiative archive)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -s y -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -l bulk -k -f -r -a '(linear completions complete string initiative archive)' -d 'Archive multiple initiatives by ID, slug, or name'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -l bulk-file -k -f -r -a '(linear completions complete string initiative archive)' -d 'Read initiative IDs from a file (one per line)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_archive' -l bulk-stdin -k -f -d 'Read initiative IDs from stdin'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a update -d 'Update a Linear initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -k -f -a '(linear completions complete string initiative update)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s w -l workspace -k -f -r -a '(linear completions complete string initiative update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s n -l name -k -f -r -a '(linear completions complete string initiative update)' -d 'New name for the initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s d -l description -k -f -r -a '(linear completions complete string initiative update)' -d 'New description'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -l status -k -f -r -a '(linear completions complete string initiative update)' -d 'New status (planned, active, completed, paused)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -l owner -k -f -r -a '(linear completions complete string initiative update)' -d 'New owner (username, email, or @me)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -l target-date -k -f -r -a '(linear completions complete string initiative update)' -d 'Target completion date (YYYY-MM-DD)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -l color -k -f -r -a '(linear completions complete string initiative update)' -d 'Initiative color (hex, e.g., #5E6AD2)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -l icon -k -f -r -a '(linear completions complete string initiative update)' -d 'Initiative icon name'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s i -l interactive -k -f -d 'Interactive mode for updates'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a unarchive -d 'Unarchive a Linear initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_unarchive' -k -f -a '(linear completions complete string initiative unarchive)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_unarchive' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_unarchive' -s w -l workspace -k -f -r -a '(linear completions complete string initiative unarchive)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_unarchive' -s y -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_initiative_unarchive' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a delete -d 'Permanently delete a Linear initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -k -f -a '(linear completions complete string initiative delete)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -s w -l workspace -k -f -r -a '(linear completions complete string initiative delete)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -s y -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -l bulk -k -f -r -a '(linear completions complete string initiative delete)' -d 'Delete multiple initiatives by ID, slug, or name'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -l bulk-file -k -f -r -a '(linear completions complete string initiative delete)' -d 'Read initiative IDs from a file (one per line)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_delete' -l bulk-stdin -k -f -d 'Read initiative IDs from stdin'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a add-project -d 'Link a project to an initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_add_project' -k -f -a '(linear completions complete string initiative add-project)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_add_project' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_add_project' -s w -l workspace -k -f -r -a '(linear completions complete string initiative add-project)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_add_project' -l sort-order -k -f -r -a '(linear completions complete number initiative add-project)' -d 'Sort order within initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_add_project' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative' -k -f -a remove-project -d 'Unlink a project from an initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_remove_project' -k -f -a '(linear completions complete string initiative remove-project)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_remove_project' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_remove_project' -s w -l workspace -k -f -r -a '(linear completions complete string initiative remove-project)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_remove_project' -s y -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_initiative_remove_project' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a initiative-update -d 'Manage initiative status updates (timeline posts)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -s w -l workspace -k -f -r -a '(linear completions complete string initiative-update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -k -f -a create -d 'Create a new status update for an initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -k -f -a '(linear completions complete string initiative-update create)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -s w -l workspace -k -f -r -a '(linear completions complete string initiative-update create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -l body -k -f -r -a '(linear completions complete string initiative-update create)' -d 'Update content (markdown)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -l body-file -k -f -r -a '(linear completions complete string initiative-update create)' -d 'Read content from file'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -l health -k -f -r -a '(linear completions complete string initiative-update create)' -d 'Health status (onTrack, atRisk, offTrack)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -s i -l interactive -k -f -d 'Interactive mode with prompts'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update' -k -f -a list -d 'List status updates for an initiative'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_list' -k -f -a '(linear completions complete string initiative-update list)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_list' -s w -l workspace -k -f -r -a '(linear completions complete string initiative-update list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_list' -s j -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_initiative_update_list' -l limit -k -f -r -a '(linear completions complete number initiative-update list)' -d 'Limit results'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a label -d 'Manage Linear issue labels'
complete -c linear -n '__fish_linear_using_command __linear_label' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_label' -s w -l workspace -k -f -r -a '(linear completions complete string label)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_label' -k -f -a list -d 'List issue labels'
complete -c linear -n '__fish_linear_using_command __linear_label_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_label_list' -l team -k -f -r -a '(linear completions complete string label list)' -d 'Filter by team (e.g., TC). Shows team-specific labels only.'
complete -c linear -n '__fish_linear_using_command __linear_label_list' -l workspace -k -f -d 'Show only workspace-level labels (not team-specific)'
complete -c linear -n '__fish_linear_using_command __linear_label_list' -l all -k -f -d 'Show all labels (both workspace and team)'
complete -c linear -n '__fish_linear_using_command __linear_label_list' -s j -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_label' -k -f -a create -d 'Create a new issue label'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s w -l workspace -k -f -r -a '(linear completions complete string label create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s n -l name -k -f -r -a '(linear completions complete string label create)' -d 'Label name (required)'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s c -l color -k -f -r -a '(linear completions complete string label create)' -d 'Color hex code (e.g., #EB5757)'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s d -l description -k -f -r -a '(linear completions complete string label create)' -d 'Label description'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s t -l team -k -f -r -a '(linear completions complete string label create)' -d 'Team key for team-specific label (omit for workspace label)'
complete -c linear -n '__fish_linear_using_command __linear_label_create' -s i -l interactive -k -f -d 'Interactive mode (default if no flags provided)'
complete -c linear -n '__fish_linear_using_command __linear_label' -k -f -a delete -d 'Delete an issue label'
complete -c linear -n '__fish_linear_using_command __linear_label_delete' -k -f -a '(linear completions complete string label delete)'
complete -c linear -n '__fish_linear_using_command __linear_label_delete' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_label_delete' -s w -l workspace -k -f -r -a '(linear completions complete string label delete)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_label_delete' -s t -l team -k -f -r -a '(linear completions complete string label delete)' -d 'Team key to disambiguate labels with same name'
complete -c linear -n '__fish_linear_using_command __linear_label_delete' -s f -l force -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a document -d 'Manage Linear documents'
complete -c linear -n '__fish_linear_using_command __linear_document' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_document' -s w -l workspace -k -f -r -a '(linear completions complete string document)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_document' -k -f -a list -d 'List documents'
complete -c linear -n '__fish_linear_using_command __linear_document_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_document_list' -s w -l workspace -k -f -r -a '(linear completions complete string document list)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_document_list' -l project -k -f -r -a '(linear completions complete string document list)' -d 'Filter by project (slug or name)'
complete -c linear -n '__fish_linear_using_command __linear_document_list' -l issue -k -f -r -a '(linear completions complete string document list)' -d 'Filter by issue (identifier like TC-123)'
complete -c linear -n '__fish_linear_using_command __linear_document_list' -l json -k -f -d 'Output as JSON'
complete -c linear -n '__fish_linear_using_command __linear_document_list' -l limit -k -f -r -a '(linear completions complete number document list)' -d 'Limit results'
complete -c linear -n '__fish_linear_using_command __linear_document' -k -f -a view -d 'View a document\'s content'
complete -c linear -n '__fish_linear_using_command __linear_document_view' -k -f -a '(linear completions complete string document view)'
complete -c linear -n '__fish_linear_using_command __linear_document_view' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_document_view' -s w -l workspace -k -f -r -a '(linear completions complete string document view)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_document_view' -l raw -k -f -d 'Output raw markdown without rendering'
complete -c linear -n '__fish_linear_using_command __linear_document_view' -s w -l web -k -f -d 'Open document in browser'
complete -c linear -n '__fish_linear_using_command __linear_document_view' -l json -k -f -d 'Output full document as JSON'
complete -c linear -n '__fish_linear_using_command __linear_document' -k -f -a create -d 'Create a new document'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -s w -l workspace -k -f -r -a '(linear completions complete string document create)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -s t -l title -k -f -r -a '(linear completions complete string document create)' -d 'Document title (required)'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -s c -l content -k -f -r -a '(linear completions complete string document create)' -d 'Markdown content (inline)'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -s f -l content-file -k -f -r -a '(linear completions complete string document create)' -d 'Read content from file'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -l project -k -f -r -a '(linear completions complete string document create)' -d 'Attach to project (slug or ID)'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -l issue -k -f -r -a '(linear completions complete string document create)' -d 'Attach to issue (identifier like TC-123)'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -l icon -k -f -r -a '(linear completions complete string document create)' -d 'Document icon (emoji)'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -s i -l interactive -k -f -d 'Interactive mode with prompts'
complete -c linear -n '__fish_linear_using_command __linear_document_create' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_document' -k -f -a update -d 'Update an existing document'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -k -f -a '(linear completions complete string document update)'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -s w -l workspace -k -f -r -a '(linear completions complete string document update)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -s t -l title -k -f -r -a '(linear completions complete string document update)' -d 'New title for the document'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -s c -l content -k -f -r -a '(linear completions complete string document update)' -d 'New markdown content (inline)'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -s f -l content-file -k -f -r -a '(linear completions complete string document update)' -d 'Read new content from file'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -l icon -k -f -r -a '(linear completions complete string document update)' -d 'New icon (emoji)'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -s e -l edit -k -f -d 'Open current content in $EDITOR for editing'
complete -c linear -n '__fish_linear_using_command __linear_document_update' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_document' -k -f -a delete -d 'Delete a document (moves to trash)'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -k -f -a '(linear completions complete string document delete)'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -s w -l workspace -k -f -r -a '(linear completions complete string document delete)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -s y -l yes -k -f -d 'Skip confirmation prompt'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -l no-color -k -f -d 'Disable colored output'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -l bulk -k -f -r -a '(linear completions complete string document delete)' -d 'Delete multiple documents by slug or ID'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -l bulk-file -k -f -r -a '(linear completions complete string document delete)' -d 'Read document slugs/IDs from a file (one per line)'
complete -c linear -n '__fish_linear_using_command __linear_document_delete' -l bulk-stdin -k -f -d 'Read document slugs/IDs from stdin'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a completions -d 'Generate shell completions.'
complete -c linear -n '__fish_linear_using_command __linear_completions' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_completions' -k -f -a bash -d 'Generate shell completions for bash.'
complete -c linear -n '__fish_linear_using_command __linear_completions_bash' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_completions_bash' -s n -l name -k -f -r -a '(linear completions complete string completions bash)' -d 'The name of the main command.'
complete -c linear -n '__fish_linear_using_command __linear_completions' -k -f -a fish -d 'Generate shell completions for fish.'
complete -c linear -n '__fish_linear_using_command __linear_completions_fish' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_completions_fish' -s n -l name -k -f -r -a '(linear completions complete string completions fish)' -d 'The name of the main command.'
complete -c linear -n '__fish_linear_using_command __linear_completions' -k -f -a zsh -d 'Generate shell completions for zsh.'
complete -c linear -n '__fish_linear_using_command __linear_completions_zsh' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_completions_zsh' -s n -l name -k -f -r -a '(linear completions complete string completions zsh)' -d 'The name of the main command.'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a config -d 'Interactively generate .linear.toml configuration'
complete -c linear -n '__fish_linear_using_command __linear_config' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_config' -s w -l workspace -k -f -r -a '(linear completions complete string config)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear' -k -f -a schema -d 'Print the GraphQL schema to stdout'
complete -c linear -n '__fish_linear_using_command __linear_schema' -s h -l help -x -k -f -d 'Show this help.'
complete -c linear -n '__fish_linear_using_command __linear_schema' -s w -l workspace -k -f -r -a '(linear completions complete string schema)' -d 'Target workspace (uses credentials)'
complete -c linear -n '__fish_linear_using_command __linear_schema' -l json -k -f -d 'Output as JSON introspection result instead of SDL'
complete -c linear -n '__fish_linear_using_command __linear_schema' -s o -l output -k -f -r -a '(linear completions complete string schema)' -d 'Write schema to file instead of stdout'
