#:schema /var/home/jonas/Development/helix-config-schema/helix-languages-schema.json

# ── Dockerfile ─────────────────────────────────────────────────────

[language-server.docker-language-server]
command = "docker-language-server"
args = ["start", "--stdio"]

[language-server.ty]
command = "uvx"
args = ["ty", "server"]

[language-server.ruff]
command = "uvx"
args = ["ruff", "server"]

[language-server.typescript-language-server]
command = "bunx"
args = ["typescript-language-server", "--stdio"]

[language-server.svelteserver]
command = "bunx"
args = ["svelte-language-server", "--stdio"]

# ── TypeScript ──────────────────────────────────────────────────────

[[language]]
name = "dockerfile"
language-servers = ["docker-language-server"]

# ── Language servers ────────────────────────────────────────────────

[[language]]
name = "typescript"
formatter = { command = "bunx", args = [
  "prettier",
  "--parser",
  "typescript",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true

# ── JavaScript ──────────────────────────────────────────────────────

[[language]]
name = "javascript"
formatter = { command = "bunx", args = [
  "prettier",
  "--parser",
  "babel",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true

# ── JSX / TSX ───────────────────────────────────────────────────────

[[language]]
name = "jsx"
formatter = { command = "bunx", args = [
  "prettier",
  "--parser",
  "babel",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "bunx", args = [
  "prettier",
  "--parser",
  "typescript",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true

# ── Svelte ──────────────────────────────────────────────────────────

[[language]]
name = "svelte"
formatter = { command = "bunx", args = [
  "prettier",
  "--plugin",
  "prettier-plugin-svelte",
  "--parser",
  "svelte",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true

# ── Python ──────────────────────────────────────────────────────────

[[language]]
language-servers = ["ty", "ruff"]
name = "python"
formatter = { command = "uvx", args = [
  "ruff",
  "format",
  "--quiet",
  "--stdin-filename",
  "%{buffer_name}",
  "-",
] }
auto-format = true

# ── JSON / CSS ──────────────────────────────────────────────────────

[[language]]
name = "json"
formatter = { command = "bunx", args = [
  "prettier",
  "--parser",
  "json",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "bunx", args = [
  "prettier",
  "--parser",
  "css",
  "--stdin-filepath",
  "%{buffer_name}",
] }
auto-format = true
